### ISSUE TITLE
Step by step installation guide

### ISSUE THREAD

**Issue by mf-sourav** [brightsign/node.js-starter-project#2]
Hi guys,
- this repo is very informative but we need a step step by step guide to run node js on brightsign player it seems extremely complex for a newbie like me.
- it would be great if you guys can have a tutorial video.
Thanks

**Comment by mf-sourav** [comment]
Hi,

- i have run webpack to generate www.zip & node-server.zip added to presentation properties>files.
- added node-server.brs to presentation properties>autorun>script.
still there is nothing on my side i checked the log whether node server is initialized still nothing
Please help out

**Comment by Khobalt** [comment]
Hey there,
sorry to have left you screaming into the void.
Please head over to our forums:
https://brightsign.zendesk.com/hc/en-us/community/topics/200594547-Forums-BrightSign-General-Discussion

Our support team doesn't really have eyes on Github yet.
